steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/fluid-analogy-364409/flask-cicd-gcp', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/fluid-analogy-364409/flask-cicd-gcp']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'flask-cicd-gcp', '--image', 'gcr.io/fluid-analogy-364409/flask-cicd-gcp', '--region', 'europe-west1']
images:
- gcr.io/fluid-analogy-364409/flask-cicd-gcp
